# Generated by Django 5.1.3 on 2024-12-03 13:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateField(auto_now_add=True, verbose_name='criado em')),
                ('modified', models.DateField(auto_now=True, verbose_name='modificado em')),
                ('cisterna', models.CharField(blank=True, max_length=10, null=True, verbose_name='Nº Cisterna')),
                ('volume', models.PositiveIntegerField(blank=True, null=True, verbose_name='Volume')),
                ('status', models.CharField(choices=[('V', 'Visitar'), ('A', 'Abastecer')], default='V', max_length=1, verbose_name='status')),
                ('entregue', models.BooleanField(blank=True, default=False, verbose_name='Entregue')),
                ('titular', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='titulares', to='usuarios.titular')),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='Motorista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt_entrega', models.DateField(blank=True, null=True)),
                ('nome', models.CharField(blank=True, max_length=50, null=True)),
                ('placa', models.CharField(blank=True, max_length=50, null=True)),
                ('km', models.FloatField()),
                ('volume', models.CharField(blank=True, max_length=50, null=True)),
                ('pedido', models.ManyToManyField(to='pedido.pedido')),
            ],
        ),
        migrations.CreateModel(
            name='PedidoAbastecer',
            fields=[
            ],
            options={
                'verbose_name': 'Pedido para Abastecer',
                'verbose_name_plural': 'Pedido para Abastecer',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('pedido.pedido',),
        ),
        migrations.CreateModel(
            name='PedidoVisitar',
            fields=[
            ],
            options={
                'verbose_name': 'Pedido de visita',
                'verbose_name_plural': 'Pedido de visita',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('pedido.pedido',),
        ),
    ]
