# Generated by Django 5.1.3 on 2025-01-12 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedido', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='pendente',
            field=models.BooleanField(blank=True, default=False, verbose_name='Pendente'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='status',
            field=models.CharField(choices=[('V', 'Visitar'), ('A', 'Abastecer'), ('P', 'Pendente')], default='V', max_length=1, verbose_name='status'),
        ),
    ]
