# Generated by Django 5.1.3 on 2025-01-12 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedido', '0002_pedido_pendente_alter_pedido_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='pendente',
        ),
        migrations.AddField(
            model_name='pedido',
            name='tipo',
            field=models.CharField(choices=[('V', 'Visita'), ('A', 'Abastecimento')], default='V', max_length=1, verbose_name='tipo'),
        ),
    ]
